### ISSUE TITLE
import load_credentials return an error

### ISSUE THREAD

**Issue by AnaValeriaS** [twitterdev/search-tweets-python#100]
Hi, I get the error below after running from searchtweets import load_credentials

Traceback (most recent call last):

  File "C:\Program Files\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-21-e1fa4616111b>", line 1, in <module>
    from searchtweets import load_credentials

  File "C:\Program Files\Anaconda3\lib\site-packages\searchtweets\__init__.py", line 4, in <module>
    from .result_stream import ResultStream, collect_results

  File "C:\Program Files\Anaconda3\lib\site-packages\searchtweets\result_stream.py", line 95
    logger.error(f"HTTP Error code: {resp.status_code}:{resp.text}")
                                                                                                    ^
SyntaxError: invalid syntax

**Comment by igorbrigadir** [comment]
> SyntaxError: invalid syntax

Maybe the yaml configuration file with your keys may be malformed (it's nearly always white space, since it's syntax in yaml). I'd run it through a YAML validator or compare the format to one of the examples.

**Comment by AnaValeriaS** [comment]
I'm using Python 3.8. 
To solve this issue, I just commented this line to run my code, but I think it is necessary to review this issue.

**Comment by jimmoffitt** [comment]
I haven't been able to reproduce this, but I am not testing on Windows. 

Not sure why that line would be flagged for invalid syntax when there are several other logger.error("") statements in that ```retry``` function.  

FWIW, the current release has that line as ```logger.error(f" HTTP Error code: {resp.status_code}: {resp.text} | {resp.reason}")```.
