### ISSUE TITLE
Twitter Premium API did not work for a specific User handle

### ISSUE THREAD

**Issue by arvindiitm** [twitterdev/search-tweets-python#103]
I was using twitter premium API for 30 days and full archive endpoints in Sandbox env. But both the endpoint is not working for a specific user handle(@WNBA). Though I am able to fetch the tweets for this handle using standard search API. I did not face any issue with other user handles.

Can anyone please advise me whats could be the reason for this? Thanks in advance.

**Comment by jimmoffitt** [comment]
Hello there. Are you still having issues with a handle-specific query? I am unable to reproduce this behavior, and there is nothing in the client code that is "query aware", other than receiving an error response with a query with bad syntax is requested.
