### ISSUE TITLE
Entities extracted from truncated text, not full text of Tweet

### ISSUE THREAD

**Issue by malidzanko** [twitterdev/search-tweets-python#104]
The field 'hashtags' only contains hashtags that can be found in 'text', not in the 'all_text'. Also, all the entities in the entities field of the Tweet object are extracted from the truncated version of the Tweet, not the extended one. Don't know if this is desired behaviour, but in my opinion it is a bug because it leads to unexpected results. 

For example:

> #Capaci #15novembre2020 seconda domenica di #zonaarancione per la #Sicilia ..... #arancione dunque ma finirà, ma l'azzurro del cielo e il blu del mare sono e resteranno quelli di sempre. #Sicily #COVID19 #COVIDー19 #Epidemia #coronavirus (#lungomare di #Isoladellefemmine) https://t.co/hQjxHpUEhP"

is the tweet, but these are the entities:

> `entities : {'hashtags': [{'text': 'Capaci', 'indices': [0, 7]}, {'text': '15novembre2020', 'indices': [8, 23]}, {'text': 'zonaarancione', 'indices': [44, 58]}, {'text': 'Sicilia', 'indices': [66, 74]}, {'text': 'arancione', 'indices': [81, 91]}], 'urls': [{'url': 'https://t.co/1C6C0YdTA2', 'expanded_url': 'https://twitter.com/i/web/status/1328122866324402178', 'display_url': 'twitter.com/i/web/status/1…', 'indices': [117, 140]}], 'user_mentions': [], 'symbols': []}`

Subsequently, if you call Tweet.hashtags, you only get first four hashtags in this case. 

Of course, you can get the full list by accessing the extended_tweet.entities field and parsing it from there but it adds more traction for the user.

**Comment by sparkingdark** [comment]
Want to work on it @malidzanko can you assign me?

**Comment by jimmoffitt** [comment]
Note that many of these complications go away with Twitter API v2. 
The v2 JSON structure and key names are not backward compatible with v1.1. 

So, on the new v2 branch, this issue shouldn't apply.

I am going to close for now. If you want to address this in the "premium and enterprise" branch, feel free to reopen.
