### ISSUE TITLE
Prop: Question: V2 API  endpoint: ..2/tweets/search/recent

### ISSUE THREAD

**Issue by remotejob** [twitterdev/search-tweets-python#105]
in previous API(1.1)
result was:
"1325930643247800322"	"1325929144597745665"	"True"	"fi"	"@riikkamarip Meillä oli täll....
a part of "id" and "text" a lot of other fields was in 'collect_results' func().
I particularity need  'in_reply_to_status_id_str','truncated' !

Now only:
{'id': '1334728746419576832', 'text': '#kiitollisuuskalenteri\n4. Päivä, ja olen tänään erit'}

Questions:
How I can find 'in_reply_to_status_id_str' ? 
Probably new result not truncated any more?

**Comment by jasco** [comment]
You might try adding `tweet_fields='referenced_tweets'` to `gen_request_parameters` when building your request.

**Comment by jimmoffitt** [comment]
Check out the new 'fields' and 'expansions' v2 request features: 
https://developer.twitter.com/en/docs/twitter-api/fields
https://developer.twitter.com/en/docs/twitter-api/expansions

These enable you to design the JSON payloads you need.

And yes, with the new v2 JSON payloads, we don't need to truncate any attributes.
