### ISSUE TITLE
V2 -- ERROR: Could not find a version that satisfies the requirement UNKNOWN==0.0.0

### ISSUE THREAD

**Issue by kbrown** [twitterdev/search-tweets-python#109]
**Describe the bug**
ERROR: Could not find a version that satisfies the requirement UNKNOWN==0.0.0

**To Reproduce**
pip3 install .

**Expected behavior**
no error

**Environment**
	ALL.  UNKNOWN==0.0.0 hard coded in git in requirements.txt

**Additional context**
I substituted TAR for UNKNOWN and that did not produce the desired effect either.  I know there was the election and all, and many of the insurrectionists abandoned twitter, but can we please get v2 api package in working order.  thanks. 

In all seriousness is "pip3 install ." supposed to work?  pip3 install searchtweets-v2 didn't work so trying this.

**Comment by igorbrigadir** [comment]
`pip install searchtweets-v2` should have worked - does pip give you any errors back?

in v2 branch, `requirements.txt` has a bunch of extra stuff you don't need https://github.com/twitterdev/search-tweets-python/pull/113 but that shouldn't be involved when you `pip install .`

**Comment by jimmoffitt** [comment]
Hi there, that's a good point about the requirements file. It's overdue for a refresh. With the package available it's been unfairly treated as a historical artifact ;) But it's good to have the option to not install the package and build from scratch.

**Comment by jimmoffitt** [comment]
I can not reproduce any issues with ```pip install searchtweets-v2``` 

Closing.
