### ISSUE TITLE
V2 missing the provided key: search_tweets_api

### ISSUE THREAD

**Issue by kbrown** [twitterdev/search-tweets-python#110]
**Describe the bug**
looks like v2 is looking for the old config gile

**To Reproduce**
python3 -m venv env
source env/bin/activate
pip3 install searchtweets-v2

search_tweets.py \
  --credential-file creds.yaml \
  --max-tweets 1000 \
  --results-per-call 100 \
  --query "from: SOMEBODY" \
  --print-stream

ERROR:searchtweets.credentials:anna-creds.yaml is missing the provided key: search_tweets_api
ERROR:searchtweets.credentials:Your credentials are not configured correctly and  you are missing a required field. Please see the  readme for proper configuration

cat creds.yaml 
search_tweets_v2:
  endpoint:  https://api.twitter.com/2/tweets/search/all
  consumer_key: X
  consumer_secret: X
  bearer_token: X

**Expected behavior**
Docs say search_tweets_v2 should work. Looks like using some v1 behavior

**Environment**
 - OS: macOS Big Sur
 - Python 3.7.8

**Additional context**
Really just want a command line tool for v2. way to hard

**Comment by kbrown** [comment]
Update looks like readme is wrong: search_tweets_api as key does work. Am I just using v1 API? TBD.

**Comment by lk251** [comment]
i have the same issue

**Comment by lk251** [comment]
@kbrown hold on i think i got it - try adding --credential-file-key search_tweets_v2 

It seems that --credential-file-key is the yaml key inside the credential file where the credentials ought to be stored. it defaults to search_tweets_api which is a v1.1 vestige, which shouldn't be there

**Comment by lk251** [comment]
#111

**Comment by kbrown** [comment]
@lk251 I verified that I am using the v2 parser and that the 1.1 key default search_tweets_api doesn't mean other dependencies are using incorrectly using 1.1 as I had feared.  So this is likely a bad default or documentation issue only.

**Comment by lk251** [comment]
@kbrown no worries, thanks for bringing it up, it helped to see it wasn't just me. My bad - I didn't check if other dependencies were using 1.1, I just saw that it ran. I'm sure that when the maintainers see this they'll be able to verify. Cheers!

**Comment by jimmoffitt** [comment]
Hi @Ik251 and @kbrown... I updated the default creds key to be "search_tweets_v2" as mentioned in the README. Also corrected a few instances in the README that referred to 'search_tweets_api." Sorry that was inconsistent and thanks for pointing that out!

**Comment by lk251** [comment]
cool, cheers!
