### ISSUE TITLE
v2: Incorrect Documentation for relative start_time settings

### ISSUE THREAD

**Issue by igorbrigadir** [twitterdev/search-tweets-python#117]
Following up on: https://twittercommunity.com/t/searchtweets-v2-start-time-request-param/150657/6?u=igorbrigadir

In the docs it says the format should be `d3` to specify "last 3 days" but in the code it's expecting `3d`

Docs:

https://github.com/twitterdev/search-tweets-python/blob/b45dcb1ab0b4fd57e28dfc053c35735c1c91c4e0/README.rst#L39-L41

Code:

https://github.com/twitterdev/search-tweets-python/blob/9656a8e3806ed02ef8a30631233d2a7a9fb2f7b9/searchtweets/api_utils.py#L35-L37

**Comment by igorbrigadir** [comment]
This was fixed in #118 but was closed without merging, not sure if that was intentional or not, also #121 has a small docs change but it shouldn't conflict.

**Comment by jimmoffitt** [comment]
Fixed in current README.rst
