### ISSUE TITLE
V2: Timing of calls made per request is too fast for API

### ISSUE THREAD

**Issue by headcoffin** [twitterdev/search-tweets-python#120]
**Describe the bug**
For the V1 track, you are allowed to make a certain number of requests per fifteen minutes depending on what level of access you have. How fast you make these number of requests does not matter. However, in V2, if you are doing a full archive search, you are not only limited to the number of requests made in a fifteen minute window, but also how many requests per second. So, when you use the V2 branch of searchtweets to do a full archive search, you cannot make more than one call at a time without it throwing an error. 
Here is the twitter page on rate limits that shows the 1call/1second rule: https://developer.twitter.com/en/docs/twitter-api/rate-limits

**To Reproduce**
Gain access to Twitter V2 full archive search, make a request that produces more than one call within the request, and you will start to see errors thrown. It happens with both ResultStream and collect_results.

**Expected behavior**
The error should not be thrown when you make requests even if it makes additional calls per request. A time.sleep(1) in the ResultStream loop that produces additional calls should fix this problem when making calls to the full archive search, for example.

**Environment**
 - OS: Windows
 - Python version 3.9, shell: Jupyter-Lab

**Additional context**
I am not sure how often searchtweets is used for full archive searches, but remedying this issue would make it one of the only python tools available at the moment that will correctly do Twitter API V2 full archive searches with no issues.

**Comment by jimmoffitt** [comment]
Yes, I will update the client soon. I've been using it with the Recent search endpoint, which does not have this "1 request per second" rate limit. I'll add the "wait" if the client is hitting the "all" endpoint. In the future, the "all" endpoint will likely support much higher per-second requests (to reach parity with the current 'enterprise' version it will support 20 requests per second). 

Accordingly, the wait period will eventually need to be configurable. 

Thank you!

**Comment by jimmoffitt** [comment]
In the ResultStream.stream method I added the following to the request loop:

```
#If hitting the "all" search endpoint, wait one second since that endpoint is currently
#limited to one request per sleep.
if "tweets/search/all" in self.endpoint:
     time.sleep(1)
```

I am making some other updates and will commit soon (next day or so?).
This update will land in the upcoming package release.

**Comment by headcoffin** [comment]
Thank you so much!!
