### ISSUE TITLE
Update api_example.ipynb to use gen_request_parameters

### ISSUE THREAD

**Issue by sipka** [twitterdev/search-tweets-python#124]
**Describe the bug**
The notebook api_example.ipynb still uses gen_rule_payload, which is deprecated. Update to gen_request_parameters instead.

**To Reproduce**
Run the first cell of the notebook while using v2 of the API.

**Expected behavior**
Imports the function required to specify parameters for search

**Environment**
 - OS: macOS
 - Python version 3.8.3

**Comment by jimmoffitt** [comment]
Thanks for the heads up. I went into this example and made it more applicable to v2, and removed non-v2 details such as the reference to search counts (which should be coming back to v2 soon).
