### ISSUE TITLE
cannot import name 'gen_rule_payload' from 'searchtweets'

### ISSUE THREAD

**Issue by thewires2** [twitterdev/search-tweets-python#125]
**Describe the bug**
The  'gen_rule_payload' function is not being imported .
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-11-cc6bdf300b6f> in <module>
----> 1 from searchtweets import ResultStream, load_credentials ,gen_request_parameters , gen_rule_payload

ImportError: cannot import name 'gen_rule_payload' from 'searchtweets' (/home/arnav/.local/lib/python3.8/site-packages/searchtweets/__init__.py)

```

**To Reproduce**
```
from searchtweets import ResultStream, load_credentials ,gen_request_parameters , gen_rule_payload
```

**Expected behavior**
I am trying to use the gen_rule_payload to define the rule for my queries.

**Environment**
 - OS: [Ubuntu 20.10]
 - Python version [3.8.5]

**Additional context**
jupyter-notebook : 6.0.3

**Comment by igorbrigadir** [comment]
Is this for `v2` API or `v1.1` ?

For v2, make sure https://pypi.org/project/searchtweets-v2/ is installed, 

For v1.1 it's https://pypi.org/project/searchtweets/ 

`gen_rule_payload` is in https://github.com/twitterdev/search-tweets-python/blob/master/searchtweets/api_utils.py#L86 for v1.1, and this only applies to v1.1 API

For v2, `gen_request_parameters` serves the same function there: https://github.com/twitterdev/search-tweets-python/blob/v2/searchtweets/api_utils.py#L84

**Comment by thewires2** [comment]
It works , Thanks !
