### ISSUE TITLE
No output file when using write_result_stream

### ISSUE THREAD

**Issue by parisa-zahedi** [twitterdev/search-tweets-python#128]
I am using version 2 on Mac. When I call write_result_stream function,  it does not give any error but it does not save any file.
The following is a piece of my code:
`stream_params = gen_params_from_config(config_dict)

    rs = ResultStream(tweetify=False, **stream_params)

    if config_dict.get("filename_prefix") is not None:
        stream = write_result_stream(rs,
                                     filename_prefix=config_dict.get("filename_prefix"),
                                     results_per_file=int(config_dict.get("results_per_file")))
    else:
        stream = rs.stream()`

Could you please help me!

 - OS: macOS 
 - Python version 3.8

**Comment by parisa-zahedi** [comment]
To be more precise, the output is a .json file with the following info:
{"newest_id": "126...", "oldest_id": "12...", "result_count": 498, "next_token": "b26...5"}

**Comment by igorbrigadir** [comment]
> stream = rs.stream()

This returns a generator, so you would have to iterate over this generator to actually fetch and write the tweets.

eg:

```
result = [tweet for tweet in stream]
```

**Comment by parisa-zahedi** [comment]
> > stream = rs.stream()
> 
> This returns a generator, so you would have to iterate over this generator to actually fetch and write the tweets.
> 
> eg:
> 
> ```
> result = [tweet for tweet in stream]
> ```

Thanks for your reply. I understand, however, how should I apply "results_per_file"?

**Comment by igorbrigadir** [comment]
> how should I apply "results_per_file"?

You don't need to, `write_result_stream` is itself a generator and it will handle writing out to multiple files itself, see https://github.com/twitterdev/search-tweets-python/blob/master/searchtweets/utils.py#L100 for reference
