### ISSUE TITLE
Cannot import name 'gen_rule_payload' from 'searchtweets'

### ISSUE THREAD

**Issue by slowflower** [twitterdev/search-tweets-python#146]
**Describe the bug**
Trting to import gen_rule_payload from searchtweets. Gives the error

**Environment**
 - OS: Windows 10
 - searchtweets-v2 1.1.1 with no serachtweets v1 installed

**Comment by igorbrigadir** [comment]
> gen_rule_payload is in https://github.com/twitterdev/search-tweets-python/blob/master/searchtweets/api_utils.py#L86 for v1.1, and this only applies to v1.1 API

> For v2, gen_request_parameters serves the same function there: https://github.com/twitterdev/search-tweets-python/blob/v2/searchtweets/api_utils.py#L87

Same as https://github.com/twitterdev/search-tweets-python/issues/125#issuecomment-827570321
