### ISSUE TITLE
@MBonvoy

### ISSUE THREAD

**Issue by watanabenaoyuk** [twitterdev/search-tweets-python#148]
**Describe the bug**

**To Reproduce**
Steps (and code snippet) to reproduce the behavior:

**Expected behavior**

**Environment**
 - OS: [e.g. macOS Catalina, Ubuntu 20.10]
 - Python version [e.g. 3.8]

**Additional context**

**Comment by andypiper** [comment]
Please explain this report, there is no issue described here.
