### ISSUE TITLE
python version compatibility

### ISSUE THREAD

**Issue by binaryaaron** [twitterdev/search-tweets-python#15]
The `merge_dicts` function is only compatible with Python 3.5+ due to the `{**dict1, **dict2}` syntax. It's a trivial fix to make it compatible with older versions of python 3. 

Thanks @jimmoffitt for the note.

**Comment by tonybaloney** [comment]
Also, the setup.py doesn't specify which versions of Python this package is compatible with. That should be setup to ensure 2.x users at least don't install this package if its not intended to be backward compatible

**Comment by binaryaaron** [comment]
This is a good point, and I will make that change as well.

**Comment by binaryaaron** [comment]
closed by #19 .
