### ISSUE TITLE
It collects different number of tweets, while running exactly the same query.

### ISSUE THREAD

**Issue by parisa-zahedi** [twitterdev/search-tweets-python#158]
**Describe the bug**

**To Reproduce**
Steps (and code snippet) to reproduce the behavior:

**Expected behavior**

**Environment**
 - OS: [e.g. macOS Catalina, Ubuntu 20.10]
 - Python version [e.g. 3.8]

**Additional context**

**Comment by andypiper** [comment]
Can you complete the information requested in the issue template please? Specifically the reproduction steps and code, and environment information.
