### ISSUE TITLE
handle specifiable limits (twitter dev account got suspended)

### ISSUE THREAD

**Issue by chandraveshchaudhari** [twitterdev/search-tweets-python#163]
**Describe the bug**
calling collect_results of API directly calls the API v2 without considering limits.

**To Reproduce**
for time_period in time_priod_list:
   for query in query_list:
       collect_results()

**Expected behavior**
To handle specifiable limits, search-tweets-python needs to handle limits as per my queries and pagination for each query.

**Environment**
 - OS:Ubuntu 22
 - Python version: 3.8

**Additional context**
**if this issue is not in the scope, please tell me where is pagination handling code so that I can handle it with user queries**

**Comment by igorbrigadir** [comment]
I'm not sure what you mean - rate limits are already handled, in https://github.com/twitterdev/search-tweets-python/blob/v2/searchtweets/result_stream.py#L55 decorator at request level, however - there is an edge case where in loops, calling the Academic access endpoint that has an extra 1 call per second limit, will cause a premature rate limit error, but in this case the solution is to add an extra second sleep to whatever loop you're running, so adding it to for `query in query_list:` loop should fix it.

**Comment by chandraveshchaudhari** [comment]
Thanks time.sleep() fixed the 300 request per 15 min case.
