### ISSUE TITLE
Search by coordinate

### ISSUE THREAD

**Issue by lyons7** [twitterdev/search-tweets-python#21]
Hello! Is it possible to include coordinates in the gen_rule_payload argument? Maybe this already exists but I can't find a list of optional arguments. It also seems that you have to have something in the query field right? (Ideally I'd like to collect any tweets that occurred in a specific location over a specific time period, but is that possible with the premium API?) Thanks!

**Comment by binaryaaron** [comment]
@lyons7 - It sure is! Premium and Enterprise both [support geo operators](https://developer.twitter.com/en/docs/tweets/search/guides/premium-operators). The operators have to be passed in the rule text itself, e.g.,

`(snow OR snowing) bounding_box:[west_long south_lat east_long north_lat]`.

Please see the linked docs for the full list of geo operators.

**Comment by lyons7** [comment]
Thanks!
