### ISSUE TITLE
Add more specific metadata to request headers

### ISSUE THREAD

**Issue by jrmontag** [twitterdev/search-tweets-python#30]
For the purposes of tracking usage adoption, it would be nice to include some library and version information in the HTTP requests. 

I believe the `requests` library under the hood of `searchtweets` sends something similar to `'User-Agent': 'python-requests/1.2.0'` in its requests. Perhaps we could modify the headers like (roughly): 
```python
version = searchtweets.__version__
useragent = 'search-tweets-python/{}'.format(version)
headers = {'User-Agent': useragent}
```
I'm not sure if it would be best set in the [`request()` method](https://github.com/twitterdev/search-tweets-python/blob/master/searchtweets/result_stream.py#L120) or in [the `make_session()` method](https://github.com/twitterdev/search-tweets-python/blob/master/searchtweets/result_stream.py#L30). The `requests` docs mention doing it in both places ([former](http://docs.python-requests.org/en/latest/user/quickstart/#custom-headers), [latter](http://docs.python-requests.org/en/latest/user/advanced/#prepared-requests)).

@binaryaaron @fionapigott @jeffakolb are there other metadata things that would be useful in the headers?

**Comment by binaryaaron** [comment]
I like this enhancement and think we should do it in the [`make_session`](https://github.com/twitterdev/search-tweets-python/blob/master/searchtweets/result_stream.py#L30) function.

We'll need to add the `__version__` attribute to the module as well so we can grab it programmatically.

**Comment by jrmontag** [comment]
Thanks @fionapigott!
