### ISSUE TITLE
Using more requests than expected

### ISSUE THREAD

**Issue by jcornford** [twitterdev/search-tweets-python#35]
Hi,

I'm not sure if this is a search-tweets module specific bug or if it is upstream - sorry if the latter.  I posted on the twitter developer forum but no response yet (link to forum post at bottom). 

I'm using the fullarchive endpoint with premium access and I’ve found I'm using more requests than intended (I’d like to use 1) when grabbing tweets for a handle over the last 90 days.  Passing in max_requests to ResultsStream() also doesn’t help. Finally, in this case only 88 tweets are matched by that search query. From my understanding of the docs I should only ever be using 1 request (as max results in 500 and each request returns at most 500 tweets).

```python
raw_data_test = {}

print("Starting: {} API calls used".format(ResultStream.session_request_counter))

def make_rule(handle, to_date, from_date):
    _rule_a = "from:"+handle
    rule = gen_rule_payload(_rule_a,
                        from_date=from_date,
                        to_date=to_date,
                        results_per_call=500)
    return rule

days_to_scrape = 90 
for indx_,handle_list, date in to_scrape[32:33]:
    
    to_datetime = pd.to_datetime(date)
    from_dateime = to_datetime - pd.Timedelta(days_to_scrape, unit='D')
    from_datestring = str(from_dateime.date())
    to_datestring = str(to_datetime.date())

    for handle in handle_list:
        #print(handle)
        print('collecting results...')
        search_query = make_rule(handle, to_datestring,from_datestring)

        print(search_query)
        rs = ResultStream(rule_payload=search_query,
                                      max_results=500,
                                      **search_args)

        results_list = list(rs.stream())
        print("You have used {} API calls".format(ResultStream.session_request_counter))
        raw_data_test[search_query] = results_list
        #time.sleep(2)
```

Output:
Starting: 0 API calls used
collecting results…
{“query”: “from:xxxxxx”, “maxResults”: 500, “toDate”: “201502050000”, “fromDate”: “201411070000”}
You have used 3 API calls

Please let me know if there is anything further info that would help.

Thanks!

(https://twittercommunity.com/t/using-more-requests-than-expected-with-searchtweets-module-and-fullarchive-endpoint/106722)

**Comment by binaryaaron** [comment]
Hi @jcornford - 

I believe that this behavior is expected for full-archive requests. Even if there are no tweets that match a rule for a given month, we require one request per month in the past. Your query covers three months and you use three requests. I apologize that this isn't clear in the documentation, and I will relate this to the right teams to clarify.

@andypiper or @jdemos, mind seeing this and adding any commentary as you see fit?

**Comment by jdemos** [comment]
Hi @jcornford,

Aaron is correct, the API will only return up to the `maxResults`, or 31 days – whichever condition is met first. I scanned the docs and this isn't well documented in the case of a "data" request, so I've made a note to better explain this behavior.

Sorry for the confusion.

-John

**Comment by jcornford** [comment]
Great, thanks for the clarification. Yes slight change in the docs would be helpful. 

Jonathan
