### ISSUE TITLE
doesn't work for python 2.7

### ISSUE THREAD

**Issue by nickyzhi** [twitterdev/search-tweets-python#36]
I was trying to use searchtweets in python 2.7, just tried to import searchtweets would return something like: 

return {**dict1, **dict2}
             ^
SyntaxError: invalid syntax

I changed to python 3.6 and it works fine.

**Comment by binaryaaron** [comment]
Hi @nickyzhi - What version of the package are you using?

**Comment by nickyzhi** [comment]
Hi @binaryaaron, I just used pip install an hour ago, it shows:

Successfully installed pyyaml-4.1 searchtweets-1.2.1 tweet-parser-1.13.1

and then I got the aforementioned error when I was trying to import searchtweets.

Then I tried to download the package and installed it  locally "pip install -e .", after import, I got:

File "/Users/**/search-tweets-python/setup.py", line 29, in <module>
        long_description=open('README.rst', 'r', encoding="utf-8").read(),
    TypeError: 'encoding' is an invalid keyword argument for this function

So I went to the setup.py and removed the encoding, then pip install -e . I got:

searchtweets requires Python '>=3.3' but the running Python is 2.7.10

So I switched to python3 and it works fine.

**Comment by nickyzhi** [comment]
I just saw the closed issue saying it doesn't support < python 3.3: [issue](https://github.com/twitterdev/search-tweets-python/issues/1)
