### ISSUE TITLE
Full Archive Search - handles Next token - larger than 500 results. 

### ISSUE THREAD

**Issue by BoPengGit** [twitterdev/search-tweets-python#37]
Hi,

Thanks for this wonderful package. I'm using the enterprise full archive search feature for our company and was wondering how I grab tweets that are more than 500 tweets. With requests of more than 500 tweets, there is a next token provided that will have the next 500 tweets right?

So how do I get the results of the full archive search, not just the first 500 tweets. Does this gen_rule_payload() and collect_results() functions give back all of the tweets from the full archive search, not just the first 500?

Thanks for the help!

Below is the full archive example script provided in the docs:

    rule = gen_rule_payload("from:jack", 
        from_date="2017-09-01", #UTC 2017-09-01 00:0 
        to_date="2017-10-30",#UTC 2017-10-30 00:00
        results_per_call=500)

    print(rule)

    {"query":"from:jack","maxResults":500,"toDate":"201710300000","fromDate":"201709010000"}

    tweets = collect_results(rule, max_results=500, result_stream_args=enterprise_search_args)

**Comment by jrmontag** [comment]
@BoPengGit Yes, pagination via the next token is handled automatically. Hopefully you observed that and are on your way!
