### ISSUE TITLE
How does the 'max_pages' parameter work? 

### ISSUE THREAD

**Issue by theFilipko** [twitterdev/search-tweets-python#39]
It is mentioned in the example but I could not find any usage of it in the class.

**Comment by binaryaaron** [comment]
Hi @theFilipko - I realize there is no usage example in the main documentation page, but we do have an example of using it within the `ResultStream` object  [here](https://twitterdev.github.io/search-tweets-python/searchtweets.html#searchtweets.result_stream.ResultStream) that you can see. I'll add it here as well:

```.python
>>> rs = ResultStream(**search_args, rule_payload=rule, max_pages=1)
>>> results = list(rs.stream())
```

You can also use it the flag `--max-pages`  from the command line program.

**Comment by theFilipko** [comment]
Hello @binaryaaron - Yes, I know that but if you go to the source code of `ResultStream` class, there is no parameter in the `__init__`:
`def __init__(self, endpoint, rule_payload, username=None, password=None,
                 bearer_token=None, max_results=1000,
                 tweetify=True, max_requests=None, **kwargs):` 
I am a bit new in python so please correct me if I'm missing something

**Comment by binaryaaron** [comment]
@theFilipko - I am sorry for my hasty (and incorrect) response, you're absolutely correct here. It looks like we made a mistake in our documentation and git logs - this parameter was removed as it was somewhat redundant in nature to the `max_results` parameter. We never updated the docs or the command-line arguments to reflect its removal. 

The main ways to limit your API usage are to use `max_requests` which limits the total number of API *calls* to make from any search query and `max_results` which limits the total volume of Tweets returned from any search query.

@twitterdev/des-science - let's make a note to 
- clean out this parameter from the command-line program 
- update the docstring for the `ResultStream` class
- review docs to ensure usage of both usage-limiting parameters are clear and updated
- rebuild the Sphinx API docs and other docs to reflect the above changes

@theFilipko, thank you very much for pointing this out.

**Comment by jimmoffitt** [comment]
FWIW, I just committed a code update that addressed an issue with making --max-pages requests. A separate issue was posted that an extra request was always made (e.g. if --max-pages=1 then two requests were made.)

While testing that fix, it seems all is well with the --max-pages command-line parameter.
