### ISSUE TITLE
Incorrectly getting 401 status code despite correct authentication parameters

### ISSUE THREAD

**Issue by tapans** [twitterdev/search-tweets-python#43]
Followed the readme steps to install the library via pip, added the relevant code in a file (see below), ran as python3 script, and keep getting 401 status code.

Relevant code invoking the library:

    from searchtweets import ResultStream, gen_rule_payload, load_credentials, collect_results
    premium_search_args = load_credentials("~/.twitter_keys.yaml",
                                       yaml_key="search_tweets_api",
                                       env_overwrite=False)
    rule = gen_rule_payload("beyonce", results_per_call=100) # testing with a sandbox account
    print(rule)
    print("TOKEN is: '{}'".format(premium_search_args['bearer_token']))
    tweets = collect_results(rule,
                         max_results=100,
                         result_stream_args=premium_search_args) # change this if you need to
    [print(tweet.all_text, end='\n\n') for tweet in tweets[0:10]];

Confirmed that ~/.twitter_keys.yaml has good creds and that the relevant application setup is good - was able to use the bearer token printed from the library in a curl request as follows:

    curl -X POST "https://api.twitter.com/1.1/tweets/search/30day/testing.json" -d '{"query": "beyonce", "maxResults": 100}' -H "Authorization: Bearer PASTED_TOKEN_HERE

**Comment by jrmontag** [comment]
Hi @tapans, thanks for opening an issue. Can you please paste the exact error output you're seeing, and the content of your `.twitter_keys.yaml` (with your credentials redacted)?

**Comment by tapans** [comment]
> Hi @tapans, thanks for opening an issue. Can you please paste the exact error output you're seeing, and the content of your `.twitter_keys.yaml` (with your credentials redacted)?

certainly.
1. error output:
        Grabbing bearer token from OAUTH
        {"query": "beyonce", "maxResults": 100}
        TOKEN is: REDACTED''
        retrying request; current status code: 401
        retrying request; current status code: 401
        retrying request; current status code: 401
        HTTP Error code: 401: Bad Authentication data.
        Rule payload: {'query': 'beyonce', 'maxResults': 100}
        Traceback (most recent call last):
          File "search_tweets_python_client.py", line 11, in <module>
            result_stream_args=premium_search_args) # change this if you need to
          File "/Users/tapans/workspace/search-tweets-python/searchtweets/result_stream.py", line 300, in collect_results
            return list(rs.stream())
          File "/Users/tapans/workspace/search-tweets-python/searchtweets/result_stream.py", line 202, in stream
            self.execute_request()
          File "/Users/tapans/workspace/search-tweets-python/searchtweets/result_stream.py", line 252, in execute_request
            rule_payload=self.rule_payload)
          File "/Users/tapans/workspace/search-tweets-python/searchtweets/result_stream.py", line 101, in retried_func
            raise requests.exceptions.HTTPError
        requests.exceptions.HTTPError

2. content of .twitter_keys.yaml:

    search_tweets_api:
        account_type: premium
        endpoint: https://api.twitter.com/1.1/tweets/search/30day/testing.json
        consumer_key: REDACTED
        consumer_secret: REDACTED

**Comment by tapans** [comment]
@jrmontag : I was able to make a fix for this. See PR https://github.com/twitterdev/search-tweets-python/pull/44/files

**Comment by binaryaaron** [comment]
@tapans - thank you for the PR / report; @jeffakolb has a slightly more simple way of fixing it and we're going with that. Thanks again!

**Comment by lzambranoz** [comment]
Error persists...

**Comment by jrmontag** [comment]
Hi @lzambranoz, can you share the version of the searchtweets library where you're seeing the issue and the specific error message you're observing?
