### ISSUE TITLE
Not using tweetparser

### ISSUE THREAD

**Issue by vefae** [twitterdev/search-tweets-python#45]
Hi, is it possible to get the tweet payload without lazily parsing with Tweet Parser (https://twitterdev.github.io/tweet_parser/index.html)?

**Comment by binaryaaron** [comment]
Hi @vefae - there is an boolean option, `tweetify`, that can be passed to the `ResultStream` object to not parse the tweets and deliver them as straight json.

You can see [here](https://twitterdev.github.io/search-tweets-python/searchtweets.html#module-searchtweets.result_stream) for details. If you're using the `collect_results` method, you can pass `tweetify=False` in the `result_stream_args` argument.
