### ISSUE TITLE
result_type parameter premium/enterprise search

### ISSUE THREAD

**Issue by BoPengGit** [twitterdev/search-tweets-python#46]
Hi,

For standard search, I see a search parameter "result_type" that has the options: mixed, recent, popular. For developer/enterprise search do you guys know if there is a similar parameter to sort the tweet results?

Thanks!

**Comment by jrmontag** [comment]
Hi @BoPengGit, the `result_type` parameter is not supported in Premium or Enterprise Search. You can review the full list of supported query operators for Premium (and, nearby, Enterprise) Search [here](https://developer.twitter.com/en/docs/tweets/search/overview/premium).

**Comment by BoPengGit** [comment]
Hi @jrmontag, so is there any way to return sorted tweets by relevance for premium/enterprise search? Because right now for premium, it looks like the default seems like date posted, most recent first?

Thanks for the help!

**Comment by jrmontag** [comment]
Hi @BoPengGit, I missed answering that portion of your original question. There is not currently a method for sorting the results.
