### ISSUE TITLE
Question: Premium tier API Usage Parameter

### ISSUE THREAD

**Issue by BoPengGit** [twitterdev/search-tweets-python#50]
Hi,

I have a question. I see here: https://developer.twitter.com/en/docs/developer-utilities/usage-api/overview there is an endpoint to query to see account usage for enterprise accounts. I was wondering for premium tier, is there an endpoint that I can use to see how much usage I have remaining for the month? 

Thank you.

**Comment by andypiper** [comment]
No, unfortunately this is not currently something offered. We've certainly heard this request from multiple other developers so this is something we are aware of, but I don't have any plans to report at this time. Keep an eye on the [developer platform roadmap](https://t.co/roadmap) and [developer forums](https://twittercommunity.com/c/announcements) for updates.

**Comment by BoPengGit** [comment]
Hi @andypiper ,

So can I use code to automatically login and parse the usage data myself. Because for us as a company, this information is very important to have alerts on if we're running low in usage left for the month because we don't want our dashboard to crash for our customers because twitter request usage has run out for that month. 

Thanks Andy for your help!

**Comment by BoPengGit** [comment]
Hi @binaryaaron @andypiper , that's good, the ResultStream.session_request_counter variable, but I feel safer if I got my information straight from the source. Am I allowed to use code to login to my dashboard and parse the usage for the month information from my dashboard? 

That's what I may want to use right now to know how much usage we have for the month. Then we can send an alert if the usage gets low.  

Thanks for the help!

**Comment by binaryaaron** [comment]
Ah, I see - i have *no* idea if automating your dashboard info is supported but it is clever. @EmilySheehan , @andypiper, @JessicaGarson - do you know? 

 I will make sure to tell our product and eng teams; I do think we should have an API to get that information. If we do implement it, we'll plan on supporting it in this library.

**Comment by BoPengGit** [comment]
@binaryaaron 

That's great. but for now, can I have permission to write a script that automatically logins to my dashboard, i.e. using python's urllib or something for example, and then parse the monthly usage information so we have that information available. Am I allowed to do that for now?

Thanks for the help.

**Comment by binaryaaron** [comment]
I definitely cannot give or deny you permission to do that.

**Comment by andypiper** [comment]
I'll make sure the product team is aware, and again, I totally understand the use case and question, but at this time I've got nothing to share on potential future support for this from an API perspective.
