### ISSUE TITLE
ResultStream raises a generic HTTPError

### ISSUE THREAD

**Issue by alex-p-fisher** [twitterdev/search-tweets-python#52]
After reviewing result_stream.py I noticed that the retry decorator raises an HTTPError with no context surrounding the actual HTTP code encountered. See below:
`
def retry(func):
    """
    Decorator to handle API retries and exceptions. Defaults to three retries.

    Args:
        func (function): function for decoration

    Returns:
        decorated function

    """
    def retried_func(*args, **kwargs):
        max_tries = 3
        tries = 0
        while True:
            try:
                resp = func(*args, **kwargs)

            except requests.exceptions.ConnectionError as exc:
                exc.msg = "Connection error for session; exiting"
                raise exc

            except requests.exceptions.HTTPError as exc:
                exc.msg = "HTTP error for session; exiting"
                raise exc

            if resp.status_code != 200 and tries < max_tries:
                logger.warning("retrying request; current status code: {}"
                               .format(resp.status_code))
                tries += 1
                # mini exponential backoff here.
                time.sleep(tries ** 2)
                continue

            break

        if resp.status_code != 200:
            error_message = resp.json()["error"]["message"]
            logger.error("HTTP Error code: {}: {}".format(resp.status_code, error_message))
            logger.error("Rule payload: {}".format(kwargs["rule_payload"]))
            raise requests.exceptions.HTTPError

        return resp

    return retried_func
`
Retry section of this page [https://developer.twitter.com/en/docs/tweets/search/overview/enterprise.html](url) indicates a throttling of requests when encountering a 503.  Also I'd like to be able to respond accordingly / log other HTTP error codes as well.  Are there any plans to address this or can I open a PR to do so?

**Comment by jrmontag** [comment]
Hi @alex-p-fisher, thanks for opening the issue. Let me know if I'm understanding your questions correctly - it sounds like: 
1. you'd like to see the specific codes for non-200 HTTP responses
2. you'd like conditional logic to handle the situation where non-200 responses arise and only raise the HTTPError

For 1., I believe the specific non-200 error code should be logged from the snippet you posted (`logger.error("HTTP Error code: ...`) before raising the exception. Are you seeing those logs wherever your code is running?

For 2., I don't believe there are currently plans to implement this logic, but you are welcome to open a PR with some examples of the behavior you're seeking.

Let me know if I'm misunderstanding your questions!

**Comment by alex-p-fisher** [comment]
Hello @jrmontag, thanks for getting back to me,

For 1., Yes the error is being logged as expected which is helpful but I need to be able to get the HTTP status code / message at run-time to respond accordingly in my application.

ie. raise an http error containing this contextual information when status_code != 200.

For2., I'd be happy to put in a pull request with the behavior I'm requesting.

Thanks,
Alex

**Comment by binaryaaron** [comment]
@alex-p-fisher - We'd welcome a PR! Thank you!

**Comment by alex-p-fisher** [comment]
I would like to open a pull request for this issue as well as an improvement if possible.  How do I acquire permissions to do so?

**Comment by jimmoffitt** [comment]
FWIW, this library was recently updated to better handle retries. It now makes a distinction between errors that are a "one and done" (e.g. authentication errors), and errors that are retriable (e.g. 503s and 429s). When retrying those it now implements a backoff mechanism and is not limited to 3 retries.
