### ISSUE TITLE
Failed to install by running `pip install searchtweets` on Mac

### ISSUE THREAD

**Issue by tekyyang** [twitterdev/search-tweets-python#53]
Hi there!

I got some problems when trying to install the `searchtweets` package. I run a `pip install searchtweets` but received the error 
```
....
long_description=open('README.rst', 'r', encoding="utf-8").read(),
    TypeError: 'encoding' is an invalid keyword argument for this function
------------------
Command "python setup.py egg_info" failed with error code 1 in .....
```
I'm using Mac and I'm trying both on python 2 and python 3 while got the same error. Does anyone have some hint about this? Or should I need to do anything else before installing?
Thank you!

**Comment by tekyyang** [comment]
Not sure what happened but it works now.

**Comment by manny22isaac** [comment]
I read a similar forum where a user was trying to install .pyper() but
since he had multiple versions of python running having issues. If it's
working, don't worry about it.

**Comment by binaryaaron** [comment]
@tekyyang - thank you for reporting; I'm guessing it could be related to python2/3 install issues? 

If you notice something again or can replicate it, I'd appreciate it if you could update this, but I'll close the issue for now. Thanks again.
