### ISSUE TITLE
tweet_mode

### ISSUE THREAD

**Issue by Algogator** [twitterdev/search-tweets-python#62]
How do I get the full text with tweet_mode=extended ? 

The tweets I get are truncated.

**Comment by fionapigott** [comment]
Hi,
The Tweet payload has several different fields that all contain the Tweet text, and the "text" (or "body") field is often truncated (in the case of quote Tweets, RTs, links, etc). When Tweets are returned as a Tweet object, you get access to the methods on a Tweet like tweet.all_text, which returns all of the text in a Tweet (refer to the various text methods here: https://twitterdev.github.io/tweet_parser/tweet_parser.html#tweet_parser.tweet.Tweet.all_text).
If you'd rather work with the returned JSON, you can manually transform it into a dict and use getter methods from the tweet_parser package directly (https://twitterdev.github.io/tweet_parser/tweet_parser.getter_methods.html), although I wouldn't necessarily recommend that, as it's more trouble.
Let me know if that answers your question.
Fiona

**Comment by casassg** [comment]
Leaving this for future reference, as I actually landed here with a similar question.

Premium endpoints do not need to have `tweet_mode=extended` as part of the request (not like the standard API endpoints). They already have `extended_tweet` object by default which includes the `full_text` field for the 280 chars text.

Reference: https://developer.twitter.com/en/docs/tweets/tweet-updates

**Comment by dshahrokhian** [comment]
@casassg I do not get the `extended_tweet` field when using Premium API. Any ideas?
