### ISSUE TITLE
Scraped tweets are the same for every request

### ISSUE THREAD

**Issue by Arowain** [twitterdev/search-tweets-python#65]
I'm using the **premium sandbox API** for scraping tweets and I can only scrape 100 tweets for each request, so if I need to scrape 500 tweets on one day I will need to do 5 requests. The problem is that when I scrape 100 tweets for each request it scrapes the same 100 tweets each time, so how can I make sure that the 100 tweets I scrape for a request is different from the 100 tweets for each other requests

**Comment by jrmontag** [comment]
Hi @Arowain, pagination across multiple requests should be automatically handled automatically by both the [`collect_results()` method](https://github.com/twitterdev/search-tweets-python#fast-way) ("the easy way") and the [`ResultsStream` object](https://github.com/twitterdev/search-tweets-python#working-with-the-resultstream). One quick check is to be check if you're setting the `max_results` kwarg to something unnecessarily low - that parameter sets the maximum total number of Tweets returned across all of the pagination. 

Can you include some additional information about how you're currently making your requests (including interpreter and library version numbers)?

**Comment by Arowain** [comment]
Hi @jrmontag thanks for the response.

Here is the library I used:
Name: searchtweets
Version: 1.7.4
Build: pypi_0
Channel: pypi

and here is my code:

```
data_1 = gen_rule_payload("#home", results_per_call=100, 
                        from_date="2018-12-20", #UTC 2017-09-01 00:00
                        to_date="2018-12-20",)  #UTC 2017-10-30 00:00 # testing with a sandbox account
 
tweets_1 = collect_results(data_1,
                         max_results=100,
                         result_stream_args=premium_search_args) # change this if you need to


```

And what do you mean on using `max_results` ? do you mean that if I need 500 tweets on the same day (for example 2018-12-20) I should set `results_per_call` to 500? and when I run `collect_results` it will return 500 tweets for this day or should I use a for loop?

**Comment by igorbrigadir** [comment]
I think it should work if you set `max_results=500`

`collect_results` already loops over pages / requests for you for convenience - so `max_results` is the thing to control how many tweets should be collected, and how many requests should be used up. So to get 500 tweets back, it will use 5 calls (returning 100 tweets in each "page" - set by `results_per_call`)

Hope that helps!

**Comment by fatimamb** [comment]
I tried to do it and make`max_results=500`  but i got this error 
```
retrying request; current status code: 422
retrying request; current status code: 422
retrying request; current status code: 422
HTTP Error code: 422: There were errors processing your request: Invalid 'maxResults':'500'. 'maxResults' must be an integer value greater than or equal to 10 and less than or equal to 100
Rule payload: {'query': '#شتاء_طنطورة', 'maxResults': 500, 'toDate': '201812220000', 'fromDate': '201812200000'}
```

**Comment by fatimamb** [comment]
thank you it works

**Comment by andypiper** [comment]
Great, I'm going to close this out.
