### ISSUE TITLE
ResultStream produces max_requests+1 requests

### ISSUE THREAD

**Issue by kxbmap** [twitterdev/search-tweets-python#67]
```python
search_args = load_credentials()
rule = gen_rule_payload("rule", results_per_call=100)
rs = ResultStream(rule_payload=rule,
                  max_requests=1,
                  **search_args)
tweets = list(rs.stream())
```
This `ResultStream` produces 2 requests (and `len(tweets)` will be 200).

**Comment by kxbmap** [comment]
https://github.com/twitterdev/search-tweets-python/blob/c1453961e0f9ad3942098b9d4952f9019e3ecc3e/searchtweets/result_stream.py#L217

Maybe, this line's `self.n_requests <= self.max_requests` should be `self.n_requests < self.max_requests`

**Comment by jrmontag** [comment]
Thanks for reporting, @kxbmap.

**Comment by jimmoffitt** [comment]
--max-pages number is now honored.
