### ISSUE TITLE
[QUESTION] How to make a rule to avoid retweets? 

### ISSUE THREAD

**Issue by gastondg** [twitterdev/search-tweets-python#69]
Hello, I'm getting every tweets this way:

`rule = gen_rule_payload("rihana", results_per_call=100)
tweets = collect_results(rule, max_results=100, result_stream_args=cred)
`
But I'm not interesting in retweets, so I'm wasting requests filtering tweets after I got them. 

I sincerely tried to understand the docs before asking, but I can't understand how PowerTrack Rules really work, and if they have any to do with it.

**Comment by jrmontag** [comment]
Hi @gastondg. This type of question is better suited for the [developer forums at twittercommunity.com](https://twittercommunity.com/search?q=filter%20retweets). The general PowerTrack rule you are seeking is potentially `-is:retweet`, but you can't use that rule in the Sandbox. Please see the linked forums questions, and open your own there if you have additional API product-specific questions.
