### ISSUE TITLE
Consolidate API setup boilerplate into helper function

### ISSUE THREAD

**Issue by jrmontag** [twitterdev/search-tweets-python#7]
I'm noticing a pattern in the examples (and my own code) where I create the requisite YAML file -
 containing my endpoint, account, and user creds - and then I write a line or two of JSON/dict parsing to create a `*_args` object which goes into the `collect_results()` function. Here's an example from some code I'm working on right now:

```python
with open(".twitter_keys.yaml") as f:
    creds = yaml.load(f)

search_endpoint = creds["search_api"]["endpoint"]
count_endpoint = change_to_count_endpoint(search_endpoint)

search_args = {"username": creds["search_api"]["username"],
               "password": creds["search_api"]["password"],
               #"bearer_token": creds["search_api"]["bearer_token"],
               "endpoint": search_endpoint,
               }
count_args = {"username": creds["search_api"]["username"],
              "password": creds["search_api"]["password"],
              # "bearer_token": creds["search_api"]["bearer_token"],
              "endpoint": count_endpoint,
             }    

rule = gen_rule_payload('cannes', from_date='2017-05-17', to_date='2017-05-29')

tweets = collect_results(rule, max_results=1000, result_stream_args=search_args)
```

It might be more clear to the user if we make strict expectations about the YAML contents and then used a helper function to hide the requisite YAML parsing and manipulation. I imagine replacing the above with the following: 

```python
with open(".twitter_keys.yaml") as f:
    creds = yaml.load(f)
    # this new dict has all the relevant keys for collect_results()
    api_args = get_api_args(creds)

rule = gen_rule_payload('cannes', from_date='2017-05-17', to_date='2017-05-29')

# and collect_results() could use a simple endpoint switch
tweets = collect_results(rule, max_results=1000, result_stream_args=api_args, endpoint='tweets')
```

where the `get_api_args()` handles the YAML parsing, the string manipulations for the different endpoints, and conditional logic for the existence of optional yaml keys.

This streamlines the user experience (fewer lines of code), but doesn't add much abstraction. Thoughts? If it sounds useful, I'm happy to take a first stab at it.

**Comment by binaryaaron** [comment]
I like the idea, @jrmontag. I would suggest a stronger simplification, that would be:

```.python
api_args = get_api_args(credential_file)
tweets = collect_results(rule, max_results=1000, result_stream_args=api_args, endpoint='tweets')
```
With the `tweets` endpoint being the default.

I think the structure of the yaml file should look like this:

```.yaml
twitter_search_api:
  endpoint: 
  username: 
  password:
  bearer_token:
  <other_stuff>:
```
Thoughts?

**Comment by jrmontag** [comment]
Good point - doesn't seem necessary to have the user parse the yaml :) Looks good to me, but I'd also appreciate some feedback from @jeffakolb and @fionapigott before moving forward.

**Comment by jeffakolb** [comment]
Sounds fine.

**Comment by jrmontag** [comment]
A couple more thoughts related to this issue: 
- I'm guessing we just haven't updated the main README in a while, but it should probably be the place to introduce the YAML file for authentication (possibly even include an empty one for the user to cp and modify)
- In the [command-line section](https://github.com/tw-ddis/twitter_search_api/blob/master/README.rst#using-the-comand-line-application) there is a discussion of using a config file for query arguments, but it also includes credential management. That feels confusing to me - maybe with the proposed changes in this issue we could require the same `.twitter_api_keys` across the board (CLI, or programmatic), and take the credential part out of the config file recommendation.

**Comment by binaryaaron** [comment]
@jrmontag I like all of that. Currently, there is no mention of a YAML file anywhere in the project, and the longer example of using  [here](https://github.com/tw-ddis/twitter_search_api/tree/master/examples). 

So after your updates, we can update the readme, current example in this repo, and our in-progress work.
