### ISSUE TITLE
URL-encoded special character ($) returns 422 no viable character

### ISSUE THREAD

**Issue by ibury08** [twitterdev/search-tweets-python#76]
Running:
`search_tweets.py` --credential-file .twitter_keys.yaml --max-results 100 --results-per-call 100 --filter-rule "%24tsla" --filename-prefix tsla_test --print-stream`

Returns:
`ERROR:searchtweets.result_stream:HTTP Error code: 422: There were errors processing your request: no viable alternative at character '%' (at position 1)
ERROR:searchtweets.result_stream:Rule payload: {'query': '%24tsla', 'maxResults': 100}`

Per [Standard Operator docs](https://developer.twitter.com/en/docs/tweets/rules-and-filtering/overview/standard-operators), I would expect this call to succeed. FWIW, using tweepy with the same query string, the call succeeds.

**Comment by igorbrigadir** [comment]
Try it with `--filter-rule "$tsla"` the library will encode the request properly itself

**Comment by ibury08** [comment]
`search_tweets.py --credential-file .twitter_keys.yaml --max-results 100 --results-per-call 100 --filter-rule "$tsla" --filename-prefix tsla_test --print-stream`

`ERROR:searchtweets.result_stream:HTTP Error code: 422: There were errors processing your request: Invalid 'query':''. 'query' must be a non-empty string
ERROR:searchtweets.result_stream:Rule payload: {'query': '', 'maxResults': 100}`

**Comment by igorbrigadir** [comment]
Oh, i assumed that would work the same as hashtags, but i guess not. 

Now that i look at it - it seems cashtags are treated differently and won't actually work at all unless you have "PowerTrack" or "Enterprise" https://developer.twitter.com/en/docs/tweets/rules-and-filtering/overview/operators-by-product

**Comment by jimmoffitt** [comment]
Yes, the cashtag operator is only available with the enterprise tier of search. I've confirmed that the client code works as expected when on enterprise tier.  You could try using filtering with an explicit string, e.g. \"$tsla\"
