### ISSUE TITLE
save as json

### ISSUE THREAD

**Issue by vxyzhang** [twitterdev/search-tweets-python#77]
Hi, is there a way to save all queried tweets as json files first, before parsing them into Twitter Parser?

**Comment by jrmontag** [comment]
Hi @vxyzhang, the `ResultStream` object has a `tweetify` kwarg that you can set to `False` in order to disable the Tweet Parser step: https://twitterdev.github.io/search-tweets-python/searchtweets.html#searchtweets.result_stream.ResultStream

**Comment by StormFalcon32** [comment]
@jrmontag any reason why collect_results doesn't have a tweetify kwarg?

**Comment by jrmontag** [comment]
Hi @StormFalcon32, `collect_results()` has an argument called `result_stream_args` which takes a dictionary that gets unpacked into a `ResultStream` object. I think you should be able to pass e.g.  `{'tweetify':False}`.

**Comment by StormFalcon32** [comment]
@jrmontag Ahhh thank you, that's very helpful
