### ISSUE TITLE
Dates Are Wrong

### ISSUE THREAD

**Issue by StormFalcon32** [twitterdev/search-tweets-python#80]
Using the premium full archive and search-tweets, I have found a tweet (https://twitter.com/TheFatApple/status/29118205491) that has a date of Oct 29, 2010. However, the API says it's 'created_at' attribute is November 4, 2010, which is wrong. This may be an API related bug, but I'm bringing it up here just to see if anyone else has experienced something similar

**Comment by andypiper** [comment]
I don't see where in the Tweet object the November 4 date appears - that Tweet ID has a `created_at` attribute value of `Fri Oct 29 19:56:59 +0000 2010` as far as I can see. How can I reproduce the steps you've been through?

**Comment by StormFalcon32** [comment]
Hmm that's interesting, I can send you my code and tell you what I did when I get home tonight

**Comment by StormFalcon32** [comment]
Ohh, I think the issue is not with the API, but with the Tweet parser. I was mistakenly using tweet.created_at_datetime instead of tweet['created_at'].

My main code https://pastebin.com/1VWNgXdr
InputOutput.py (just writes to csv while printing stuff) https://pastebin.com/EkiwTNDr
Some of the csv output https://pastebin.com/qWgd9Af0

The first tweet is https://twitter.com/MelissaAWardy/status/29627651793, which has a 'created_at' attribute of 'Thu Nov 04 01:33:32 +0000 2010' but str(tweet.created_at_datetime) gives 2010-11-04 01:43:01. Likewise, for the last tweet in that sample output, https://twitter.com/EconProfThomas/status/29616766978 has a 'created_at' of 'Wed Nov 03 23:22:00 +0000 2010' but a str(tweet.created_at_datetime) gives 2010-11-04 01:43:01 again.

**Comment by jimmoffitt** [comment]
Seems using tweet['created_at'] straightened this out...
