### ISSUE TITLE
HTTP Rate Limit Error on Premium Full Archive Search?

### ISSUE THREAD

**Issue by jenningsanderson** [twitterdev/search-tweets-python#81]
I have 13 similar queries, 9 of them succeed, however 4 of them error due to HTTP Rate Limiting. 

Full Error Output: 
```
ERROR:searchtweets.result_stream:HTTP Error code: 429: Exceeded rate limit
ERROR:searchtweets.result_stream:Rule payload: {
      'fromDate': '201708220000', 
      'maxResults': 500, 
      'toDate': '201709030000', 
      'query': 'from:1307298884 OR from:355574901 OR from:11996222 OR from:588649189 OR from:117808071 OR from:19401084 OR from:19401550 OR from:735608306585198592 OR from:241642996 OR from:27888518 OR from:56470183 OR from:14861004 OR from:106728683 OR from:19683725 OR from:229379349 OR from:16425419 OR from:20562924 OR from:76138084 OR from:76303 OR from:399111773 OR from:26774590 OR from:795296683533942784 OR from:159669473 OR from:345161879 OR from:4784677524 OR from:22654208 OR from:2227415623 OR from:139114806 OR from:34030321 OR from:140660078 OR from:247503175 OR from:14791386 OR from:3014668581 OR from:279136688 OR from:64798315 OR from:2247970886 OR from:704407090060730368 OR from:82960432 OR from:64523032 OR from:396045731 OR from:45564482 OR from:28645139 OR from:18205191 OR from:734824555051646976 OR from:357026180 OR from:44900997 OR from:14192680 OR from:4813084988 OR from:600958397 OR from:605603344 OR from:577537350 OR from:589419748 OR from:1429761 OR from:401527825 OR from:15937025 OR from:2788847458', 
'next': 'eyJtYXhJZCI6OTAwMjkyNzgzMzk0NjM1Nzc2fQ=='}
```

Relevant YAML configuration details: 
```
search_params:
    results-per-call: 500
    max-results: 1000000

output_params:
    save_file: True
    results_per_file: 10000000

search_tweets_api:
  account_type: premium
  endpoint: https://api.twitter.com/1.1/tweets/search/fullarchive/history.json
```

_It also appears that these failed queries also count against our paid requests, even though nothing gets written to the output file._

**Comment by zafodB** [comment]
> It also appears that these failed queries also count against our paid requests, even though nothing gets written to the output file.

I have the same issue and #40 mentions it as well. Doesn't seem like this was ever picked up, but maybe @binaryaaron would know?

Would be nice to at least be able to retrieve tweets that were fetched before the rate limit was reached.

**Comment by jenningsanderson** [comment]
@zafodB Without diving into the code, I have a hunch:

For the Premium API access, the failure appears after a few dozen seconds... perhaps at or near the one minute mark.  That is, the utility nicely handles the limit of 10 requests / second when paginating... but then at 60 seconds, it's nearly at 600 requests, at which point the Premium EndPoint returns "ERROR" because there's a limit of 60 requests / minute.

At that point, all data is lost if the utility was attempting to write results to a file.

It also appears that Enterprise accounts have variable  rate limits, but default to 120 req / minute, but not an additional requests / second limitation.

Kind of makes me miss the former GNIP API: _"Your query is running" ... "Done, here's an S3 bucket with your tweets, available for 2 weeks"_

**Comment by jimmoffitt** [comment]
I made some updates to the HTTP error handling. Previously, there was a general mechanism to retry 3 times for every error. This retry mechanism had a backoff design, but there was not a long enough delay duration to recover from a rate limit error. It also treated all errors the same, retrying three times even if your credentials were wrong. 

So, this new update does the following:
- With rate limit errors, it backs off exponentially across a fifteen-minute period and should recover from such errors and continue on.

- Retries with 5xx server-side errors.  

- All other errors (4xx) are treated as "one and done, no use and retrying..." errors.

Next step is updating the PyPi package...
