### ISSUE TITLE
[KeyError: 'maxResults'] Error when creating count_rule

### ISSUE THREAD

**Issue by gaardhus** [twitterdev/search-tweets-python#82]
I tried connecting the the Counts API endpoint via the documentation here:

https://github.com/twitterdev/search-tweets-python#counts-endpoint

`count_rule = gen_rule_payload("beyonce", count_bucket="day")`

But this throws me the following error:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-33-62bbdf3105fa> in <module>
----> 1 count_rule = gen_rule_payload('beyonce', count_bucket="day") # count_bucked may be "day", "hour" or "minute"

~\Anaconda3\lib\site-packages\searchtweets\api_utils.py in gen_rule_payload(pt_rule, results_per_call, from_date, to_date, count_bucket, tag, stringify)
    128         if set(["day", "hour", "minute"]) & set([count_bucket]):
    129             payload["bucket"] = count_bucket
--> 130             del payload["maxResults"]
    131         else:
    132             logger.error("invalid count bucket: provided {}"

KeyError: 'maxResults'
```

I ended up specifying `results_per_call=500` to the gen_rule_payload arguments, which solved my problem. However this seemed kind of scary when working with a paid API. I dont' know if this is working as intended, but please either fix documentation or code :)

**Comment by tk-90** [comment]
I get the same error but cannot even avoid it by specifying `results_per_call`. Right now it seems impossible for me to define the `count_bucket` at all. It would really be great if you could fix that issue.

**Comment by jimmoffitt** [comment]
Just committed code updates to fix this. Also updated the README, and the command-line argument descriptions. 

Attempted to make it more clear that you need to use --count-bucket to trigger a counts request, and that there was, in fact, no default. As currently coded, you need to specify a --count-bucket value.

Also, when using both --count-bucket and --results-per-call it now gracefully ignores the --results-per-call setting, which does not apply to counts requests.
