### ISSUE TITLE
Is it possible to search for more than one user in a query?

### ISSUE THREAD

**Issue by thb5018** [twitterdev/search-tweets-python#83]
Is it possible to search for created by more than one user in a query? 

Going off the following provided example: 
```
rule = gen_rule_payload("from:jack",
                        from_date="2017-09-01", #UTC 2017-09-01 00:00
                        to_date="2017-10-30",#UTC 2017-10-30 00:00
                        results_per_call=500)
```

I tried the following variations with no success: 
```
rule = gen_rule_payload("from:jack", "from:bill",
rule = gen_rule_payload('"from:jack" OR "from:bill"', 
rule = gen_rule_payload("('from:jack', 'from:bill')",
rule = gen_rule_payload("('from:jack' OR 'from:bill',
```

**Comment by thb5018** [comment]
``

**Comment by jrmontag** [comment]
@thb5018 check out [the docs here](https://developer.twitter.com/en/docs/tweets/rules-and-filtering/overview/standard-operators) for more detailed information about the construction and syntax of rules. In your case, I believe `"from:jack OR from:bill"` should accomplish your goal.

**Comment by thb5018** [comment]
@jrmontag Thanks for getting back. I was able to get it to successfully execute with `"(from:userID1 OR from:userID2)"`. 

I appreciate your help.
