### ISSUE TITLE
401 Credential Error

### ISSUE THREAD

**Issue by dmbali** [twitterdev/search-tweets-python#84]
I am getting a 401 error even though it seems I have a valid app, dev environment, and new keys/tokens.  My app is: Text Analysis Homework  17160618 and my environment name is USIRCrisis.  I refreshed my credentials and updated my yaml file, but I can't seem to get it to work.

Full error message:
retrying request; current status code: 401
HTTP Error code: 401: Invalid or expired token.
Rule payload: {'query': 'iran', 'maxResults': 100}

[BALI_MSDS696_Project - 26Mar.pdf](https://github.com/twitterdev/search-tweets-python/files/4395364/BALI_MSDS696_Project.-.26Mar.pdf)

Thanks so much for any help steering out of this!
Dawn

**Comment by jimmoffitt** [comment]
Hoping you have sorted out your authentication issues by now ;) I've recently adopted this client library... 

In cases like this, it can be helpful to test your credentials with a cURL command: 

curl -X POST "https://api.twitter.com/1.1/tweets/search/fullarchive/USIRCrisis.json" -d '{"query":"TwitterDev "search api"","maxResults":"100"}' -H "Authorization: Bearer TOKEN"
