### ISSUE TITLE
no support for tweet_mode

### ISSUE THREAD

**Issue by vinayakkailas** [twitterdev/search-tweets-python#85]
i am unable to use tweet_mode argument in the payload. Is it not being supported?

TypeError: gen_rule_payload() got an unexpected keyword argument 'tweet_mode'

**Comment by andypiper** [comment]
Tweet mode is not valid on premium and enterprise endpoints - all Tweets serve full text content.

**Comment by kfriis33** [comment]
@andypiper I'm having the same issues as #75 -- it seems like on the premium endpoint there is no 'full_text' field, and the 'text' field is truncated
