### ISSUE TITLE
current status code: 422

### ISSUE THREAD

**Issue by thomasf1** [twitterdev/search-tweets-python#86]
I´m trying to use the api from pyhton with the simplest possible setup:

```python
from searchtweets import collect_results, load_credentials, gen_rule_payload, ResultStream


premium_search_args = load_credentials("./twitter_keys.yaml", yaml_key="search_tweets_premium", env_overwrite=False)

rule = gen_rule_payload("from:jack",
						from_date="2020-01-29", #UTC 2017-09-01 00:00
						to_date="2007-10-30",#UTC 2017-10-30 00:00
						results_per_call=500)

tweets = collect_results(rule, max_results=1000, result_stream_args=premium_search_args)
```

But just get a loop of "retrying request; current status code: 422"

**Comment by jrmontag** [comment]
Hey @thomasf1, `from_date` should be the beginning of the time period over which you're querying, and `to_date` should be the end of the period. In your snippet, it looks like `from_date` is later than `to_date`. 

Unrelated to that semantic issue, I'll just highlight that querying over a 13-year period is going to require a lot of paging 😄

**Comment by thomasf1** [comment]
Thanks for the quick answer. Good Point. Strangely, I do get the same error code even without the dates.

Also, using postman, I discovered that the earliest date allowed is 200603210000 (makes sense)

However, I can´t seem to get protected tweets with the Postman API and with search-tweets-python always a 422 (even without dates)

from searchtweets import collect_results, load_credentials, gen_rule_payload, ResultStream


premium_search_args = load_credentials("./twitter_keys.yaml", yaml_key="search_tweets_premium", env_overwrite=False)

```pyhton
rule = gen_rule_payload("from:jack",
						results_per_call=500)

tweets = collect_results(rule, max_results=1000, result_stream_args=premium_s
```

**Comment by thomasf1** [comment]
PS: The endpoint is https://api.twitter.com/1.1/tweets/search/fullarchive/(myenv).json

**Comment by EmilySheehan** [comment]
Retrieving Tweets by protected accounts is not available with data products like premium Search FullArchive.
