### ISSUE TITLE
filter has:geo not working

### ISSUE THREAD

**Issue by icaroramiires** [twitterdev/search-tweets-python#87]
Hi, 

i'm execute a rule has:geo and has:retweet on method gen_rule_payload, but the api return erro: 

`rule = gen_rule_payload("beyonce", results_per_call=100)
rs = ResultStream(rule_payload=rule),
                          **self.auth)
`

`
HTTP Error code: 422: {"error":{"message":"There were errors processing your request: Reference to invalid operator 'has:geo'. Operator is not available in current product or product packaging. Please refer to complete available operator list at http://t.co/operators. (at position 13)","sent":"2020-06-11T01:05:45+00:00","transactionId":"006fd79a0024c395"}}
Request payload: {'query': 'beyonce has:geo'}
`

**Comment by andypiper** [comment]
If you have a sandbox (free) account then the `has:geo` operator is not available. You need to be in a paid Premium tier in order to use this operator.

**Comment by icaroramiires** [comment]
Thanks @andypiper!
