### ISSUE TITLE
NotATweetError with ResultStream

### ISSUE THREAD

**Issue by phze22** [twitterdev/search-tweets-python#91]
Error message: 

NotATweetError: This dict has neither 'created_at' or 'postedTime' as keys

Tweet object in v2 does not seem to have either of these fields: https://developer.twitter.com/en/docs/twitter-api/fields

{
   "data": {
       "id": "1263150595717730305",
       "public_metrics": {
           "retweet_count": 12,
           "reply_count": 14,
           "like_count": 49,
           "quote_count": 7
       },
       "text": "Do you 👀our new Tweet settings?\n\nWe want to know how and why you’d use a feature like this in the API. Get the details and let us know what you think👇\nhttps://t.co/RtMhhfAcIB https://t.co/8wxeZ9fJER"
   }

Also the expansions are not helpful here. 

Was the field deleted?

Thanks.

**Comment by phze22** [comment]
Thanks for the reponse and effort. I totally agree about default tweet fields...

rule = gen_request_parameters('kvinder',results_per_call=100,tweet_fields=["attachments","author_id","context_annotations","conversation_id","created_at","entities","geo","id","in_reply_to_user_id","lang","possibly_sensitive","referenced_tweets","source","text"])
rs = ResultStream(**search_args,
                  request_parameters=rule,
                  max_results=100,
                  max_pages=1)
tweets = list(rs.stream())

**-> Unfortunately, let me run into the next error: HTTP Error code: 400:**
{"errors":[{"parameters":{"tweet.fields":["['attachments', 'author_id', 'context_annotations', 'conversation_id', 'created_at', 'entities', 'geo', 'id', 'in_reply_to_user_id', 'lang', 'possibly_sensitive', 'referenced_tweets', 'source', 'text']"]},"message":"The `tweet.fields` query parameter value [['attachments'] is not one of [attachments,author_id,context_annotations,conversation_id,created_at,entities,geo,id,in_reply_to_user_id,lang,non_public_metrics,organic_metrics,possibly_sensitive,promoted_metrics,public_metrics,referenced_tweets,source,text,withheld]"},{"parameters":{"tweet.fields":["['attachments', 'author_id', 'context_annotations', 'conversation_id', 'created_at', 'entities', 'geo', 'id', 'in_reply_to_user_id', 'lang', 'possibly_sensitive', 'referenced_tweets', 'source', 'text']"]},....

....continuing for every field with the end comment: "title":"Invalid Request","detail":"One or more parameters to your request was invalid.","type":"https://api.twitter.com/2/problems/invalid-request"} | Bad Request

from api_utils.py of this repo: 
tweet_fields (string): comma-delimted list of Tweet JSON attributes wanted in endpoint responses. Default is "id,created_at,text").

Is there something wrong with the formatting?

**Comment by jimmoffitt** [comment]
Ah, this is probably due to the double quotes around the individual fields... at the endpoint level, it is looking for requests with the form:
https://api.twitter.com/2/tweets/search/recent?query=snow -is:retweet&tweet.fields=created_at,author_id,attachments
