### ISSUE TITLE
search_tweets.py - Remove tweet_parser import [v2]

### ISSUE THREAD

**Issue by j-bucholtz** [twitterdev/search-tweets-python#94]
After running `pip install searchtweets-v2` and manually installing python-dateutil, running `search_tweets.py -h` throws the following exception:
```bash
Traceback (most recent call last):
  File "/home/jordan/Development/test/venv/bin/search_tweets.py", line 10, in <module>
    from searchtweets import (ResultStream,
  File "/home/jordan/Development/test/venv/lib/python3.6/site-packages/searchtweets/__init__.py", line 4, in <module>
    from .result_stream import ResultStream, collect_results
  File "/home/jordan/Development/test/venv/lib/python3.6/site-packages/searchtweets/result_stream.py", line 19, in <module>
    from tweet_parser.tweet import Tweet
ModuleNotFoundError: No module named 'tweet_parser'
```

The documentation mentions tweet_parser isn't used in v2, so I removed the import in result_stream.py and was able to fetch tweets using search_tweets.py

Can this import be removed in v2?

**Comment by j-bucholtz** [comment]
I can create the PR to remove the import if you think it's acceptable.

**Comment by jimmoffitt** [comment]
Hey there, while I could not reproduce any issues with `search_tweets.py -h`, I went ahead and removed any references to the TweetParser package. Had been on my list for a while, but an earlier attempt got tripped up. 

I just updated the repository and rerolled the pypi package.

Thanks!
